pub let expression =
  #|int add(){
  #|  print 2+3+4+5;
  #|  print 0;
  #|
  #|return -1;
  #|}
  #|
  #|int main(){
  #|  print 1+(10+100)+1000;
  #|  print -1*999;
  #|  print 3/-1+125*8;
  #|  print 9*(100-1);
  #|  print 13/3;
  #|
  #|
  #|  print 100>1;
  #|  print -1==-1;
  #|  print 99<98;
  #|
  #|  int a=10;
  #|  print -a>0;
  #|  print a!=100&&-1>-2;
  #|  print 123;
  #|  print add();
  #|  
  #|  int b=20;
  #|  print a<0||b<0||b>b-a;
  #|}