# Mini C EBNF Grammar 2024

# Translation Unit
<Translation_Unit> ::= {<Function_Definition>} CODE_EOF

# Definition
<Function_Definition> ::= (VOID|INT) IDENTIFIER "(" ")" <Compound_Statement>
<LocalVariable_Definition> ::= (INT) IDENTIFIER ["="<Expression>]";"

# Statement
<Statement> ::= <LocalVariable_Definition> | <Compound_Statement> | 
                <Assign_Statement> | <Print_Statement> | <Expression_Statement>
<Compound_Statement> ::= "{"{<Statement>}"}"
<Assign_Statement> ::= IDENTIFIER "=" <Expression> ";"
<Print_Statement> ::= PRINT <Expression> ";"
<Expression_Statement> ::= <Expression> ";"

# Expression
<Expression> ::= <PlusMinus_Expression>

<PlusMinus_Expression> ::= <MulDiv_Expression>{("+" | "-")<MulDiv_Expression>}
<MulDiv_Expression> ::= <Unary_Expression>{("*" | "/" | "%")<Unary_Expression>}
<Unary_Expression> ::= ["-"]<Primary_Expression> 
<Primary_Expression> ::= "("<Expression>")" | IDENTIFIER | CONSTANT_INT